[package]
name = "easy-svg"
version = "0.4.0"
edition = "2024"
authors = ["effdotsh"]
license = "MIT"
description = "Author SVGs in Rust through a statically typed system"
homepage = "https://github.com/effdotsh/easy-svg"
readme = "README.md"
repository = "https://github.com/effdotsh/easy-svg"
keywords = ["svg", "xml", "graphics", "builder"]
categories = ["graphics", "rendering"]
include = [
    "/Cargo.toml",
    "/Cargo.lock",
    "/LICENSE",
    "/README.md",
    "/build.rs",
    "/examples/**",
    "/src/**",
    "/tests/**",
    "/SVG/developer.mozilla.org/en-US/docs/Web/SVG/Attribute/*.html",
    "/SVG/developer.mozilla.org/en-US/docs/Web/SVG/Element/*.html",
]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }

[lints.rust]
unused_variables = { level = "deny" }
unused_imports = { level = "deny" }

[lints.clippy]
pedantic = { level = "warn" }
nursery = { level = "warn" }
cargo = { level = "warn" }
cognitive_complexity = { level = "warn" }
new_without_default = { level = "deny", priority = 2 }

[build-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
scraper = "0.23"
syn = "2.0.106"
prettyplease = "0.2.37"
proc-macro2 = "1.0.101"
